sudo: false
language: ruby

rvm:
- ruby-head
- 2.5.1
- 2.4.4
- 2.3.7
- 2.2.9
- 2.1
- 2.0
- jruby-head
- jruby-9.1.16.0

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: 2.0
    - rvm: 2.1
    - rvm: 2.2
#   fast_finish: true
